[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=2.18.2",
    "dash-svg>=0.0.12",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
